### ISSUE TITLE
Need help on installing in Node-red

### ISSUE THREAD

**Issue by gruijter** [solick/node-red-contrib-netgear#1]
Hi Lyn,

Nice work! I want to try it in node-red, but I'm stuck installing in. I'm kind of a noob in Node-red...

This is what I tried:
1) Open node-red browser, go to 'manage palette', go to tab 'install' and search for 'node-red-contrib-netgear'
> result: the plugin doesn't show up

2) go to command line (on a rpi), go to '$HOME/.node-red', do `npm i node-red-contrib-netgear`, do `node-red-restart`
> result: in the palette I see a new node, but with an error, and I can not select a netgear node on the left side. See image below

![2020-10-24](https://user-images.githubusercontent.com/19174120/97078273-7a66fe00-15eb-11eb-8c48-503cd32a7dc7.png)

**Comment by solick** [comment]
@gruijter hi sorry I missed the change in publishing nodes to Node-RED repo this April. There is now an extra step to do. I pushed Version 0.0.3 and installed it successfully from the pallette and was able to fetch the devices. Please check if its now working for you.

**Comment by gruijter** [comment]
Yes, working ok now with the new version 0.0.3

Thx!

**Comment by Hacksore** [comment]
@solick I found it quite annoying to have to click the button so I created a GitHub action.

It is necessary to have publishing to npm  automated for this to make sense though.
https://github.com/marketplace/actions/node-red-flow

**Comment by solick** [comment]
@Hacksore thanks will have a look into it
